apiVersion: v1
kind: Pod
metadata:
  name: vpn-gw
  annotations:
    v1.multus-cni.io/default-network: '[{ "name": "macvlan-conf-dhcp" , "mac" : "74:3F:ED:1F:8D:55" }]'
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
  containers:
  - name: vpn-gw
    image: reg.epsilon.pt/dsnx:latest
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
      - name: kmods
        mountPath: /lib/modules
  volumes:
    - name: kmods
      hostPath:
        path: /lib/modules
